# Default values for container1.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: lejeunen/container2

resources:
  requests:
    memory: "1024M"
    cpu: "1"
  limits:
    memory: "1024M"


env:
  - name: JVM_OPTS
    value: "-Xmx600M"